#pragma once
#include "smart_ptr.h"

PTR( Animation );

class Animation {
public:
enum MOTION {
	MOTION_PLAYER_KNIGHT_WAIT,
	MOTION_PLAYER_KNIGHT_WALK,
	MOTION_PLAYER_KNIGHT_ATTACK,
	MOTION_PLAYER_KNIGHT_DEAD,
	MOTION_PLAYER_MONK_WAIT,
	MOTION_PLAYER_MONK_WALK,
	MOTION_PLAYER_MONK_ATTACK,
	MOTION_PLAYER_MONK_DEAD,
	MOTION_PLAYER_HUNTER_WAIT,
	MOTION_PLAYER_HUNTER_WALK,
	MOTION_PLAYER_HUNTER_ATTACK,
	MOTION_PLAYER_HUNTER_DEAD,
	MOTION_MINOTAUR_WAIT,
	MOTION_MINOTAUR_WALK,
	MOTION_MINOTAUR_CLEAVE,
	MOTION_MINOTAUR_DAMAGE,
	MOTION_MINOTAUR_DEAD,
	MOTION_MINOTAUR_SMASH,
	MOTION_MINOTAUR_DASH,
	MOTION_GHOST_WAIT,
	MOTION_GHOST_WALK,
	MOTION_GHOST_ATTACK,
	MOTION_GHOST_DAMAGE,
	MOTION_GHOST_DEAD,
	MOTION_ARMOR_WAIT,
	MOTION_ARMOR_WALK,
	MOTION_ARMOR_ATTACK,
	MOTION_ARMOR_DAMAGE,
	MOTION_ARMOR_DEAD,
	MOTION_GOBLIN_WAIT,
	MOTION_GOBLIN_WALK,
	MOTION_GOBLIN_ATTACK,
	MOTION_GOBLIN_DAMAGE,
	MOTION_GOBLIN_DEAD,
	MOTION_CYCLOPS_WAIT,
	MOTION_CYCLOPS_WALK,
	MOTION_CYCLOPS_ATTACK,
	MOTION_CYCLOPS_DAMAGE,
	MOTION_CYCLOPS_DEAD,
	MOTION_DEEDBOX,
	MOTION_MAX
};
public:
	Animation( MOTION motion = MOTION_MAX, double anim_speed = 1.0 );
	virtual ~Animation( );
public:
	void update( );
	bool isEndAnimation( ) const;
	int getMotion( ) const;
	double getAnimTime( ) const;
	void setAnimationTime( double anim_time );
private:
	double _anim_time;
	double _max_anim_time;
	double _anim_speed;
	MOTION _motion;
};

