#pragma once
#include "smart_ptr.h"
#include "mathmatics.h"

PTR( Effect );

class Effect {
public:
	enum EFFECT {
		EFFECT_FAIRY,
		EFFECT_DAMAGE,
		EFFECT_PLAYER_ATTACK_SLASH,
		EFFECT_PLAYER_ATTACK_SWORD,
		EFFECT_PLAYER_ATTACK_STAB,
		EFFECT_PLAYER_ATTACK_EXCARIBUR,
		EFFECT_PLAYER_ATTACK_JAB,
		EFFECT_PLAYER_ATTACK_IMPACT,
		EFFECT_PLAYER_ATTACK_UPPER,
		EFFECT_PLAYER_ATTACK_RUSH,
		EFFECT_PLAYER_ATTACK_BEAM,
		EFFECT_PLAYER_ATTACK_BUBBLE,
		EFFECT_PLAYER_ATTACK_LAY,
		EFFECT_PLAYER_ATTACK_SPLASH,
		EFFECT_PLAYER_ATTACK_FIRE,
		EFFECT_PLAYER_ATTACK_RAPID_FIRE,
		EFFECT_PLAYER_ATTACK_SHOT,
		EFFECT_PLAYER_ATTACK_BULLET_RAIN,
		EFFECT_PLAYER_KNIGHT_STORE,
		EFFECT_PLAYER_MONK_STORE,
		EFFECT_PLAYER_WITCH_STORE,
		EFFECT_PLAYER_HUNTER_STORE,
		EFFECT_ENEMY_ATTACK_FIRE_BALL,
		EFFECT_BOSS_ATTACK_FIRE,
		EFFECT_BOSS_ATTACK_BOMBING,
		EFFECT_BOSS_HIT_EXPLOSION,
		EFFECT_BOSS_HIT_CIRCLE,
		EFFECT_PICKUP_CRYSTAL,
		EFFECT_MAX,
	};
public:
	Effect( );
	virtual ~Effect( );
public:
	int setEffect( EFFECT effect );
	void drawEffect(int playing_handle, Vector scale, Vector pos, Vector dir);
	void deletEffect( int effect_handle );
};

